# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-30 07:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('pub_date', models.DateTimeField(auto_now_add=True)),
                ('text', models.TextField()),
                ('shorturl', models.CharField(max_length=255)),
                ('image1', models.FileField(blank=True, null=True, upload_to='static/images/blog/')),
                ('image2', models.FileField(blank=True, null=True, upload_to='static/images/blog/')),
                ('image3', models.FileField(blank=True, null=True, upload_to='static/images/blog/')),
                ('image', models.FileField(blank=True, null=True, upload_to='static/images/blog/')),
            ],
        ),
    ]
