# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-30 07:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(choices=[('T', '\u0422\u043e\u043c\u0430\u0442\u044b'), ('V', '\u041e\u0432\u043e\u0449\u0438'), ('D', '\u0414\u0435\u043a\u043e\u0440\u0430\u0442\u0438\u0432\u043d\u044b\u0435')], max_length=1)),
                ('name', models.CharField(max_length=255)),
                ('extra', models.CharField(blank=True, choices=[('ind', '\u0418\u043d\u0434\u0435\u0442\u0435\u0440\u043c\u0438\u043d\u0430\u043d\u0442\u043d\u044b\u0435'), ('pin', '\u041f\u043e\u043b\u0443\u0438\u043d\u0434\u0435\u0442\u0435\u0440\u043c\u0438\u043d\u0430\u043d\u0442\u043d\u044b\u0435'), ('det', '\u0414\u0435\u0442\u0435\u0440\u043c\u0438\u043d\u0430\u043d\u0442\u043d\u044b\u0435')], max_length=3, null=True)),
                ('description', models.TextField()),
                ('price', models.CharField(max_length=255)),
                ('imagename', models.FileField(blank=True, null=True, upload_to='static/images/catalogue/')),
            ],
        ),
    ]
